### ISSUE TITLE
spi and i2c problem!

### ISSUE THREAD

**Issue by monster-xie** [Wei1234c/SX127x_driver_for_MicroPython_on_ESP8266#12]
I use the esp32 with oled board. pin define same as your code,but the spi for lora and i2c for oled don't work.

**Comment by Wei1234c** [comment]
The SPI communication often failed on the OLED ESP32 DevKit. It fails after h/w reset until s/w reset.
Try soft reset (ctrl-D) it.

**Comment by monster-xie** [comment]
when ctrl-D，then get the picture below，oled no display？

![image](https://user-images.githubusercontent.com/5821515/56456151-e2a3a680-639a-11e9-96e0-d2b7c7a5875d.png)

**Comment by Wei1234c** [comment]
Please trace the "config_lora.py" file to see whether the right controller_xx.py is selected.

**Comment by Wei1234c** [comment]
Please trace the "config_lora.py" file to see whether the right controller_xx.py is selected.

**Comment by monster-xie** [comment]
controller_esp_ttgo_lora_oled imported but not display!

**Comment by Wei1234c** [comment]
I just flash and re-upload the code. It works perfectly on my ESP32-LoRa-OLED DevKit. 
Maybe the OLED display on your borard is out of order.
