### ISSUE TITLE
RSSI for the ESP32

### ISSUE THREAD

**Issue by davefes** [Wei1234c/SX127x_driver_for_MicroPython_on_ESP8266#17]
Running `LoraReceiver.py` I get:

`RSSI<bound method>`

The register 0x1a reads 00 and 0x2c reads 00

Looking through all the examples I get the impression that RSSI is only available on the TTGO LORA OLED device.

I downloaded the schematic for the T3_V1.6 TTGo LORA device and don't see any special RSSI-related hardware.

Is there a way to get RSSI using the ESP32?

Thank you.

**Comment by Wei1234c** [comment]
There is a bug in `LoraReceiver.py `. 
Please download the file again.

**Comment by davefes** [comment]
Thank you very much.
