### ISSUE TITLE
Run Time Error

### ISSUE THREAD

**Issue by rahulrksmau** [Wei1234c/SX127x_driver_for_MicroPython_on_ESP8266#3]
Error is showing when I am trying to run Example code.
I am using RPi 3 B and LoRa sx1278 rf 433 .

I want to communicate between these two RPi using this LoRa .

pi@raspberrypi:~/Downloads/SX127x_driver_for_MicroPython_on_ESP8266/examples/DuplexCallback $ python3 main.py 

home/pi/Downloads/SX127x_driver_for_MicroPython_on_ESP8266/examples/DuplexCallback/controller_rpi.py:9: RuntimeWarning: No channels have been set up yet - nothing to clean up!  Try cleaning up at the end of your program instead!
  GPIO.cleanup()
/home/pi/Downloads/SX127x_driver_for_MicroPython_on_ESP8266/examples/DuplexCallback/controller_rpi.py:52: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(pin_id, in_out) 
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    test.main() 
  File "/home/pi/Downloads/SX127x_driver_for_MicroPython_on_ESP8266/examples/DuplexCallback/test.py", line 41, in main
    pin_id_RxDone = config_lora.Controller.PIN_ID_FOR_LORA_DIO0)
  File "/home/pi/Downloads/SX127x_driver_for_MicroPython_on_ESP8266/examples/DuplexCallback/controller.py", line 64, in add_transceiver
    transceiver.init()        
  File "/home/pi/Downloads/SX127x_driver_for_MicroPython_on_ESP8266/examples/DuplexCallback/sx127x.py", line 97, in init
    raise Exception('Invalid version.')
Exception: Invalid version.

**Comment by Wei1234c** [comment]
"Exception: Invalid version." means RPi cannot communicate with SX1278 via SPI interface.  Mostly due to pins being connected in-correctly.

**Comment by Wei1234c** [comment]
It has been 4 days since my reply, close this issue now.
