### ISSUE TITLE
Tabs/spaces error on several files in demo

### ISSUE THREAD

**Issue by rcludwick** [Wei1234c/SX127x_driver_for_MicroPython_on_ESP8266#7]
Three of the files in demo are tabbed immediately followed by lines that are space indented.  This causes the following errors when building a custom micropython build for the esp32.

Traceback (most recent call last):
  File "modules/sx127x/demo/LoRaDuplex.py", line 46
IndentationError: unindent does not match any outer indentation level
../../py/mkrules.mk:116: recipe for target 'build/frozen_mpy/sx127x/demo/LoRaDuplex.mpy' failed

Traceback (most recent call last):
  File "modules/sx127x/demo/LoRaReceiver.py", line 10
IndentationError: unindent does not match any outer indentation level
../../py/mkrules.mk:116: recipe for target 'build/frozen_mpy/sx127x/demo/LoRaReceiver.mpy' failed
make: *** [build/frozen_mpy/sx127x/demo/LoRaReceiver.mpy] Error 1

Traceback (most recent call last):
  File "modules/sx127x/demo/LoRaSetSpread.py", line 49
IndentationError: unindent does not match any outer indentation level
../../py/mkrules.mk:116: recipe for target 'build/frozen_mpy/sx127x/demo/LoRaSetSpread.mpy' failed
make: *** [build/frozen_mpy/sx127x/demo/LoRaSetSpread.mpy] Error 1

**Comment by Wei1234c** [comment]
Thanks!

The files with indenting errors were fixed and pushed to GitHub minutes ago.
