### ISSUE TITLE
Import loops in config_lora.py and controller.py

### ISSUE THREAD

**Issue by rcludwick** [Wei1234c/SX127x_driver_for_MicroPython_on_ESP8266#8]
After looking through your code, the way the imports are done will probably cause problems.

config_lora.py imports controller_esp which then import config_lora.py, which then imports controller_esp and so on. 

The problem I have is that code is run in the module body, so it makes it really hard to reason about what's going on, when.

I've done a partial refactoring of your code to something I think will work better in my fork.  It's not complete, but should maybe give you an idea of how to fix it.

https://github.com/rcludwick/SX127x_driver_for_MicroPython_on_ESP8266/blob/master/src/sx127x/config.py

**Comment by Wei1234c** [comment]
To my understanding via experience with MicroPython, the "import" mechanism is somewhat different from that of CPython. General speaking, it is more "lazy loading", and load only once.  In any sense my code seems working fine for now being. 
Thank you for attention and please keep me informed.

**Comment by rcludwick** [comment]
Hi,

Thanks for the hard work.

So that may be true of mpy, but it looks like this code is meant to be used on a PC an rpi as well.

So in that case you should probabpy remove that code and simplify the code base quite a bit.

**Comment by Wei1234c** [comment]
The code actually works fine on RPi. Readme.md shows the experments, in Chinese thought. Code review is alway benefitual and wecome, I will have a look of your fork later.

**Comment by rcludwick** [comment]
One thing I wanted to do was to fix the namespace issues so I can just drop
sx127x into the modules directory of the esp32 port of micropython and
build it.

So it will probably be a massive change for reorganization and a little
refactoring, but most of the internal logic will remain the same, if that
makes sense.

**Comment by Wei1234c** [comment]
Just had a quick view of your code, which basicaly uses a singleton factory class. That maybe a good way of doing it too. 

In my code, I just utilize Python's "import one" mechanism as a pattern of singleton.

**Comment by rcludwick** [comment]
I did... it was import errors.  :)  Soooo... I just refactored it.  Most of your code is good but I just wanted to make it easier for myself to use in the future.

So the good news is that the bulk of the refactoring is done in sx127x, and now I can just symlink in the sx127x into modules for the esp32 port, and build without errors.


>>> from sx127x.config import CONFIG

>>> CONFIG.CONTROLLER
<class 'ESP32Controller'>


1.  Renamed the base controller is now BaseController, and then all the other controllers subclass off the BaseController.  

2.  To prevent namespace conflicts I gave each Controller it's own name.  ESP32Controller, TTGOController, etc.  This is mostly for tests, but it's kind of nice to see what type the Controller really is.

3.  Singleton pattern for config, but you knew this.  :)

Other than the structure, your actual logic should still the same.  I've got a fresh build flashed to my TTGO, and I'm going to test it out this evening.

**Comment by rcludwick** [comment]
One thing to think about is maybe since it looks like the Controllers are setting up the pins on "import" which might surprise some people, maybe a better solution is to setup the esp32/esp8266/rpi hardware during SX127x.init()?

**Comment by carterw** [comment]
I agree that the imports are awkward. I've been using a lot of this code and had to totally reorganize all of the files to make a more rational hierarchy (I am using it with ESP32 micropython). 

I've found that the Controller class is an okay place to receive the set of pins that have to be initialized and perform that, and for setting up the SPI bus. Then the SX127x class can expect all the pins etc to work as expected. There are a lot of device parameters that can be adjusted in that class too. I made a method that can let me set them as needed based on a parameters file that I read in at runtime. That way I can tweak things without having to modify the code.

**Comment by rcludwick** [comment]
So I've looked at it a bit more, and I feel like the sx172x should own the controller.  

There's some dynamic code that probably could be done other ways through object compositiion  (controller.add_transceiver(), controller.prepare_spi(), etc.)

**Comment by Wei1234c** [comment]
Your help is appreciated.

 However, please make sure 1) a controller can work with multiple transceivers. 2) The same code should work with ESP8266/ESP32/RPi without any modifcation.

Pull request is welcome, but I am afraid that I have no time to do those test.

**Comment by rcludwick** [comment]
In all honesty, I won't be able to test multiple platforms.  I feel like maybe it's best I just fork it at this point.

**Comment by rcludwick** [comment]
FYI:  A bunch of updates have been made in my fork.  The duplex code seems to work, but I do have one minor bug to fix.
